config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "front#index"
  resources :front,only:[:index]
  


  resources 'guest'
  resources :front,only: [:index]

  resources :access,only: [:index]
  resources :private,only: [:index]




  resources :shopping do
    collection do
      get  'purchase/:id'=>  'shopping#purchase', as: 'purchase'
      post 'pay/:id'=>   'shopping#pay', as: 'pay'#httpメソッドはpostなので注意
      get  'done/:id'=>      'shopping#done', as: 'done'
    end
  end
  


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guest.rb
class Guest < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :src, ImageUploader
  belongs_to :shopping
end

app/models/shopping.rb
class Shopping < ApplicationRecord
  has_many :images,dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  validates :name,presence: true
  validates :price,presence: true
  validates :explain,presence: true
  validates :number,presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/access_controller.rb
class AccessController < ApplicationController
  def index 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/front_controller.rb
class FrontController < ApplicationController
  def index

  end
end

app/controllers/guest_controller.rb
class GuestController < ApplicationController

  def index
    
    @guests = Guest.all
    
  end


  def new
    @guest = Guest.new
  end

  def create
    @guest = Guest.new(guest_params)
    if @guest.save
      flash[:denger] = "ありがとうございます。商品を承りました"
      redirect_to new_guest_path
    else 
      flash[:denger] = "まだ未入力のものがあります。"
      redirect_to new_guest_path
    end

  end


  def destroy
    @guest = Guest.find_by(id:params[:id])
    @guest.destroy
    redirect_to guest_index_path

  end




  private
  def guest_params
    params.require(:guest).permit(:name,:kana,:phone_number,:mail,:adress_number,:adress,:number) 
  end





end

app/controllers/private_controller.rb
class PrivateController < ApplicationController
  http_basic_authenticate_with :name => ENV['BASIC_AUTH_USERNAME'], :password => ENV['BASIC_AUTH_PASSWORD'] if Rails.env == "production"

  def index
  end
  
end

app/controllers/shopping_controller.rb
class ShoppingController < ApplicationController
  def index
    # basic
    @shopping = Shopping.includes(:images)
  end

  def create
    @shopping = Shopping.new(shop_params)
    if @shopping.save
      redirect_to shopping_index_path
    else
      redirect_to new_shopping_path
    end

  end



  def new
    @shopping = Shopping.new
    @shopping.images.new
  end


  def show

    @shopping = Shopping.find_by(id:params[:id])

  end



  def destroy
    @shopping = Shopping.find_by(id:params[:id])
    @shopping.destroy
    redirect_to shopping_index_path


  end


  def edit
    @shopping = Shopping.find_by(id: params[:id])
  end
  def update
    @shopping = Shopping.find_by(id: params[:id])
    @shopping.update(shop_params)
    redirect_to shopping_index_path,notice: '商品を編集しました'
  end


  def purchase
    @shopping = Shopping.find_by(id:params[:id])
  end



  def pay
    @shopping = Shopping.find(params[:id])
    Payjp.api_key =  ENV['sk_key']
    charge = Payjp::Charge.create(
    amount: @shopping.price,
    card: params['payjp-token'],
    currency: 'jpy'
    )
    redirect_to  done_shopping_index_path
  end

  private
  def shop_params
    params.require(:shopping).permit(:name,:price,:explain,:number,images_attributes: [:src]) 
  end


  def basic
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USERNAMES'] && password ==  ENV['BASIC_AUTH_PASSWORDS'] 
    end
  end





end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/front_helper.rb
module FrontHelper
end

app/helpers/guest_helper.rb
module GuestHelper
end

app/helpers/private_helper.rb
module PrivateHelper
end

app/helpers/shopping_helper.rb
module ShoppingHelper
end

app/views/access/index.html.haml
.title
  access
.acccessBox
  .access
    
    %iframe{:allowfullscreen => "", "aria-hidden" => "false", :frameborder => "0", :height => "450", :src => "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12851.038528896606!2d139.3887268!3d36.3666007!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x99fa368f059662f3!2z576O5a655a6kIFRFRERZIEJPWSdT!5e0!3m2!1sja!2sjp!4v1595314549781!5m2!1sja!2sjp", :style => "border:0;", :tabindex => "0", :width => "500"}
    
    
    
  .link
    .adress
      TEDDY　BOY'S
      %br
      %br
      栃木県足利市葉鹿町2丁目30-5
      %br
      %br
      TEL 0284-64-1301
      %br
      %br
      定休日：毎週火曜日、他。
      %br
      %br
      営業時間：9:30～19:00
      


    %br
    %br
    %br
    %br


%br

app/views/front/index.html.haml
.shop_image
  .slide

    =image_tag 'top.png', alt: 't'

   




.explain-box
  
  .explain
    このページはティディーボーイズのオンラインショップページです。
  
    .send
      =link_to 'ホームページはこちら','https://teddyboys.jp/' 


  %br
  %br
  %br
  %br
  .send
    =link_to 'Shoppingへ',shopping_index_path 

app/views/guest/index.html.haml
- @guests.each  do |shopper| 
  .guets_shopper
    
    = "お客様名:#{shopper.name}"
    %br
    = "かな:#{shopper.kana }"
    %br
    ="電話番号:#{shopper.phone_number}" 
    %br
    ="  メールアドレス:#{shopper.mail}"
    %br
    ="郵便番号:#{shopper.adress_number}"
    %br
    ="お届け先:#{shopper.adress}"
    %br
    = "商品番号:#{shopper.number}"
  .sakujyo
    = link_to "削除",guest_path(shopper),method: :delete,data:{confirm: "削除しますか？"}

app/views/guest/new.html.haml
.flash
  =flash[:denger]


.form
  = form_for @guest,url: guest_index_path do |f|

    .name_guest
      お名前
      = f.text_field :name,placeholder:"ex 山田　太郎"
    .kana_guest
      カナ
      = f.text_field :kana, placeholder: "ex ヤマダ　タロウ"
    .phone_number_guest
      電話番号
      = f.text_field :phone_number,placeholder:"ex 080-1234-5678"
    .mail_guest
      メールアドレス
      = f.text_field :mail, placeholder:"ex sarai@gmail.com"
    .adress_number_guest
      郵便番号
      = f.text_field :adress_number, placeholder:"ex 321-1234"
    .adress_guest
      お届け先住所
      = f.text_field :adress,placeholder:"ex 栃木県　足利市　堀込町9-3-44 マンション名　１０２"

    .number
      商品番号
      = f.text_field :number,placeholder:"ex 2番"

    =f.submit "確定する",data:{confirm: "お間違いはないですか？"},class: "send"
     



  
     

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title 美容室 TEDDY BOY'S
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .header
      .home 
        = link_to 'home',root_path
      .shopping
        = link_to 'shopping',shopping_index_path
      .link 
        = link_to 'access', access_index_path	
      .private 
        = link_to 'private(staff only)',private_index_path
    = yield

app/views/private/index.html.haml
.product
  = link_to '商品を出品する',new_shopping_path


.guests
  = link_to 'お客様情報確認',guest_index_path


.guests
  - if user_signed_in?
    = link_to 'ログアウト',destroy_user_session_path,method: :delete
  - else
    = link_to 'ログイン',new_user_registration_path

app/views/shopping/_shopping.html.haml
.items
  - @shopping.each do |member|
    .item
        

      .image
        = image_tag("#{member.images.first.src}")
      .name
        ="商品名:#{member.name}"
      %br
      .price
        ="値段:¥#{member.price}(送料税込)"
      %br

      .explains
        ="#{member.explain}"
      %br
      .shousai
        = link_to "詳しく見る",shopping_path(member.id),class:"shosaiz"


      - if user_signed_in?
        .sakujyo

          = link_to "削除",shopping_path(member),method: :delete
        .edit
          = link_to "編集",edit_shopping_path(member.id)

app/views/shopping/done.html.haml
.flash_box
  .flash
    ご購入ありがとうございます。続けてお客様情報をご入力ください！！！！

  %br
  %br
  %br
  %br
  %br
  %br


  = link_to "お客様情報入力へ",new_guest_path,class:"send"

app/views/shopping/edit.html.haml
= form_for @shopping,url: shopping_path(@shopping),method: :patch do |f|

  .name 
    商品名
    = f.text_field :name 
  .price
    値段
    = f.text_field :price
  .explains
    商品説明
    = f.text_field :explain
  .number
    商品番号
    = f.text_field :number
  .images

    = f.fields_for :images do |i| 
      = i.file_field :src 


  = f.submit "確定する",class:"send" 

app/views/shopping/index.html.haml
.title
  shopping


.itemsBox
  =render "shopping"

app/views/shopping/new.html.haml
= form_for @shopping,url: shopping_index_path do |f|
  .name 
    商品名
    = f.text_field :name 
  %br
  .price
    値段
    = f.text_field :price
  %br
  .explains
    商品説明
    = f.text_field :explain
  %br
  .number
    商品番号
    %br
    = f.text_field :number
  %br
  .images

    = f.fields_for :images do |i| 
      = i.file_field :src 
    
  = f.submit "確定する",class:"send" 

app/views/shopping/purchase.html.haml
.itemsBox_show
  .items_show
    .image_show
      =image_tag("#{@shopping.images.first.src}")

    .name_show
      
      = "商品名:#{@shopping.name }"
    .price_show
      = "価格:¥#{@shopping.price}(送料税込)"
    .explains_show
      = "説明:#{@shopping.explain}"
    .number_show
      = "商品番号:#{@shopping.number}"

    .areat
      ※商品決済後、お届け先住所等のお客様情報のご入力となります
  .a
  = form_tag(action: :pay, method: :post) do
    :plain
    %script{type: "text/javascript", src: "https://checkout.pay.jp", class:"payjp-button", "data-text": "購入する", "data-key": "pk_test_6c62395ff5328b141cf685a4"}

app/views/shopping/show.html.haml
.itemsBox_show
  .items_show
    .image_show
      =image_tag("#{@shopping.images.first.src}")

    .name_show
      
      = "商品名:#{@shopping.name }"
    .price_show
      = "価格:¥#{@shopping.price}(送料税込)"
    .explains_show
      = "説明:#{@shopping.explain}"
    .number_show
      = "商品番号:#{@shopping.number}"
    .areat
      購入の際,商品番号を入力していただきますので、お控えをお願いいたします。


    .buy
      =link_to '購入画面へ', purchase_shopping_index_path,data:{confirm: "商品番号は控えましたか？お客様自身に不備があった場合、当店は責任を一切おいかねますのでご了承ください"},class:"send"